version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(pathname)s:%(lineno)d - %(message)s'

# filters:
#   until_info:
#     (): logging_course.filters.MaxLevelFilter
#     max_level: INFO

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: ../../../data/logs/app.log
    maxBytes: 1048576 # 1 MB
    backupCount: 5
    encoding: utf8

root:
  level: WARNING
  handlers: [console, file_handler]

loggers:
  my_module:
    level: DEBUG
